
import { GeoJSONData } from './types';

export const RAW_GEOJSON_DATA: GeoJSONData = {
  "type": "FeatureCollection",
  "features": [
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.750443,38.465686]},"properties":{"item":"http://www.wikidata.org/entity/Q1013468","itemLabel":"Kaymaklı Underground City","typeLabel":"Underground City","heritageLabel":"UNESCO World Heritage","adminLabel":"Nevşehir","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Kaymakl%C4%B1%20Underground%20City%20large%20room.JPG","kulturenvanteriID":"3338"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.735034,38.373403]},"properties":{"item":"http://www.wikidata.org/entity/Q1328958","itemLabel":"Derinkuyu Underground City","typeLabel":"Underground City","heritageLabel":"UNESCO World Heritage","adminLabel":"Derinkuyu","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Derinkuyu%20Underground%20City%209831%20Nevit%20Enhancer.jpg","kulturenvanteriID":"3335"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.480277777,38.493083333]},"properties":{"item":"http://www.wikidata.org/entity/Q25378109","itemLabel":"Topada Rock Inscription","typeLabel":"Archaeological Site","adminLabel":"Acıgöl","kulturenvanteriID":"65883"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.725,38.628055555]},"properties":{"item":"http://www.wikidata.org/entity/Q28221127","itemLabel":"Nevşehir Museum","typeLabel":"Museum","adminLabel":"Nevşehir","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Nev%C5%9Fehir%20museum%20in%202019%201556.jpg","kulturenvanteriID":"3922"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.85,38.66667]},"properties":{"item":"http://www.wikidata.org/entity/Q64705367","itemLabel":"Göreme National Park","typeLabel":"National Park","heritageLabel":"UNESCO World Heritage","adminLabel":"Nevşehir","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Vallegoreme2.jpg"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.805555555,38.630333333]},"properties":{"item":"http://www.wikidata.org/entity/Q112865630","itemLabel":"Uçhisar Castle","typeLabel":"Castle","adminLabel":"Uçhisar","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Nev%C5%9Fehir%20U%C3%A7%20hisar%20kalesi.jpg","kulturenvanteriID":"3055"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.839127063,38.6386709]},"properties":{"item":"http://www.wikidata.org/entity/Q109519139","itemLabel":"El Nazar Church","typeLabel":"Rock Church","adminLabel":"Göreme","kulturenvanteriID":"3307"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.61553812,38.747929248]},"properties":{"item":"http://www.wikidata.org/entity/Q131526402","itemLabel":"St Demetrius Church","typeLabel":"Church","adminLabel":"Gülşehir","kulturenvanteriID":"3293"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.863055555,38.652777777]},"properties":{"item":"http://www.wikidata.org/entity/Q620593","itemLabel":"Göreme Valley","typeLabel":"Fairy Chimney","heritageLabel":"UNESCO World Heritage","adminLabel":"Nevşehir","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Goreme%20valley.jpg","kulturenvanteriID":"2028"}},
    {"type":"Feature","geometry":{"type":"Point","coordinates":[34.846267,38.6387]},"properties":{"item":"http://www.wikidata.org/entity/Q114383869","itemLabel":"Dark Church","typeLabel":"Rock Church","heritageLabel":"UNESCO World Heritage","adminLabel":"Göreme","image":"http://commons.wikimedia.org/wiki/Special:FilePath/Dark%20Church%20%28Karanl%C4%B1k%20Kilise%29%20in%20Cappadocia%2C%20G%C3%B6reme.jpg"}}
  ]
};
